### ISSUE TITLE
New waiting queue system

### ISSUE THREAD

**Issue by damiankrzyz** [FrostyApeOne/FrostyBot#2]
First of all thank you for releasing this to public. It's very kind of you.

I was wondering if you could look into this? Curry has recently introduced a queueing systtem that is crashing the bot.

![Screenshot 2021-03-01 at 20 57 04](https://user-images.githubusercontent.com/79311645/109557969-b85fbb80-7ad0-11eb-9560-430426d6a00c.png)

Traceback (most recent call last):
  File "frostyBot-3070-GB-RTX-VISION.py", line 193, in <module>
    checkStock()
  File "frostyBot-3070-GB-RTX-VISION.py", line 51, in checkStock
    raise Exception("InStock")
Exception: InStock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frostyBot-3070-GB-RTX-VISION.py", line 207, in <module>
    acceptCookies = addButton = browser.find_element_by_id("onetrust-accept-btn-handler")
  File "/Users/damiankrzyzanowski/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/damiankrzyzanowski/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/damiankrzyzanowski/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/damiankrzyzanowski/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="onetrust-accept-btn-handler"]"}
  (Session info: chrome=88.0.4324.192)

**Comment by FrostyApeOne** [comment]
Thank you for bringing it up, however I no longer work on this project and I don't maintain it. I have now started working on a new version which is .Net based. Not released yet but will be in a week time (hopefully if everything goes ok) 
Please feel free to join the discord server for the latest news and announcements https://discord.gg/yGCrZQbY
